apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dbnetapp
  name: dbnetapp
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: postgres:10
      generation: null
      importPolicy: {}
      name: "10"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
